CREATE TABLE `User`(
	`bundles` VARCHAR(10),
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`SoftDeleteFlag` BOOLEAN,
	`user` VARCHAR(10),
	`user_id` VARCHAR(50) NOT NULL,
	PRIMARY KEY(`user_id`)
);
ALTER TABLE `User`
	ADD CONSTRAINT `eaa51b14e79fa812160854a067118e` UNIQUE KEY(`user_id`);
