if(typeof(com)=== "undefined"){ com = {}; }
if(typeof(com.kony)=== "undefined"){ com.kony = {}; }
if(typeof(com.kony.EMPLOYEE)=== "undefined"){ com.kony.EMPLOYEE = {}; }
if(typeof(com.kony.EMPLOYEE.EMPLOYEE)=== "undefined"){ com.kony.EMPLOYEE.EMPLOYEE = {}; }

//API call will trigger EMPLOYEE reset
com.kony.EMPLOYEE.EMPLOYEE.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("EMPLOYEE",successcallback,errorcallback);
}



if(typeof(com)=== "undefined"){ com = {}; }
if(typeof(com.kony)=== "undefined"){ com.kony = {}; }
if(typeof(com.kony.ESS)=== "undefined"){ com.kony.ESS = {}; }
if(typeof(com.kony.ESS.MYTIME)=== "undefined"){ com.kony.ESS.MYTIME = {}; }
if(typeof(com.kony.ESS.MYTIME.MyTime)=== "undefined"){ com.kony.ESS.MYTIME.MyTime = {}; }

//API call will trigger MyTime reset
com.kony.ESS.MYTIME.MyTime.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("MyTime",successcallback,errorcallback);
}



if(typeof(com)=== "undefined"){ com = {}; }
if(typeof(com.kony)=== "undefined"){ com.kony = {}; }
if(typeof(com.kony.MYTIME)=== "undefined"){ com.kony.MYTIME = {}; }
if(typeof(com.kony.MYTIME.Notifications)=== "undefined"){ com.kony.MYTIME.Notifications = {}; }

//API call will trigger Notifications reset
com.kony.MYTIME.Notifications.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("Notifications",successcallback,errorcallback);
}




// **********************************Start Scope definition************************
konysyncClientSyncConfig ={
     "AppID": "1000000020ac26b7c",
     "Version": "dea4400a4bac1a48a70dfa9e8d2c4c33a90ed1f6c7135da21d76760bf4aef56d",
     "ArrayOfSyncScope": [
          {
               "ScopeName": "EMPLOYEE",
               "ScopeTables": [
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "Communication_Type_Id",
                              "Employee_Id"
                         ],
                         "Columns": [
                              {
                                   "Length": 4,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Communication_Type_Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employee_Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "END_DATE"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "START_DATE"
                              },
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Value"
                              }
                         ],
                         "Name": "Communication_Channel"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "Employee_Id",
                              "Id"
                         ],
                         "Columns": [
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employee_Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 4,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Type"
                              }
                         ],
                         "Name": "Communication_Type"
                    },
                    {
                         "Relationships": {"ManyToOne": [
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "Id",
                                        "TargetObject_Attribute": "Employee_Id"
                                   }],
                                   "TargetObject": "Communication_Channel",
                                   "Cascade": "false"
                              },
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "Media_Id",
                                        "TargetObject_Attribute": "name"
                                   }],
                                   "TargetObject": "mediaEmployee",
                                   "Cascade": "false"
                              }
                         ]},
                         "Pk_Columns": [
                              "Id",
                              "User_Id"
                         ],
                         "Columns": [
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Blood_group"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "date",
                                   "Name": "Date_of_birth"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Department_Id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Designation_Id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employment_Type"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "First_Name"
                              },
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Gender"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "group_id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 255,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Interests"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "IsEmployee"
                              },
                              {
                                   "Length": 64,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Job_Location"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "date",
                                   "Name": "JoiningDate"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Last_Name"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Manager_Id"
                              },
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Marital_Status_Id"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "date",
                                   "Name": "Marriage_date"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Media_Id"
                              },
                              {
                                   "Length": 255,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Medical_needs"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Middle_Name"
                              },
                              {
                                   "Length": 100,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Nationality"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Office_Id"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Physical_disability"
                              },
                              {
                                   "Length": 100,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Place_of_birth"
                              },
                              {
                                   "Length": 100,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Preffered_name"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "RH_factor"
                              },
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Suffix"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Title"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "User_Id",
                                   "IsPrimaryKey": true
                              }
                         ],
                         "Name": "Employee"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["Holiday_Date"],
                         "Columns": [
                              {
                                   "Length": 10,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Holiday_Date",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Name"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Type"
                              }
                         ],
                         "Name": "Holiday"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["Id"],
                         "Columns": [
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "lastmodifiedts"
                              },
                              {
                                   "Length": 1,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "softdeleteflag"
                              },
                              {
                                   "Length": 255,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Status_Name"
                              }
                         ],
                         "Name": "Status"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["name"],
                         "Columns": [
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "classField"
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "classValue"
                              },
                              {
                                   "Length": 60,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "description"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "extension"
                              },
                              {
                                   "Length": 20,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "group"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "true",
                                   "type": "string",
                                   "Name": "name",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 20,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "ondemand"
                              },
                              {
                                   "Length": 15,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "type"
                              },
                              {
                                   "IsNullable": true,
                                   "type": "integer",
                                   "Name": "blobref_url"
                              },
                              {
                                   "metadata": {
                                        "extension": "extension",
                                        "format": "type",
                                        "description": "description",
                                        "id": "name",
                                        "contentType": "URL"
                                   },
                                   "Length": 0,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "binary",
                                   "downloadToDevice": "ondemand",
                                   "downloadToDeviceField": "ondemand",
                                   "Name": "url"
                              }
                         ],
                         "Name": "mediaEmployee"
                    }
               ],
               "Strategy": "OTA_SYNC",
               "ScopeDatabaseName": "1000000020ac26b7c",
               "DataSource": "b66987d8-93f4-42d2-8485-74a049499092"
          },
          {
               "ScopeName": "MyTime",
               "ScopeTables": [
                    {
                         "Relationships": {},
                         "Pk_Columns": ["Id"],
                         "Columns": [
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employee_Id"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "End_Date"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 1,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "isBillable"
                              },
                              {
                                   "Length": 7,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Planned_Hours"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Project_Code"
                              },
                              {
                                   "Length": 256,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Project_Description"
                              },
                              {
                                   "Length": 128,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Project_Name"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Project_Type"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Start_Date"
                              }
                         ],
                         "Name": "Project"
                    },
                    {
                         "Relationships": {"OneToMany": [
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "Project_Id",
                                        "TargetObject_Attribute": "Id"
                                   }],
                                   "TargetObject": "Project",
                                   "Cascade": "false"
                              },
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "Task_Id",
                                        "TargetObject_Attribute": "Id"
                                   }],
                                   "TargetObject": "Task",
                                   "Cascade": "false"
                              }
                         ]},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employee_Id"
                              },
                              {
                                   "Length": 6,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "date",
                                   "Name": "End_Date"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 5,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Planned_Hours"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Project_Id"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Start_Date"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Task_Id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Type"
                              },
                              {
                                   "Length": 50,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "User_Id"
                              }
                         ],
                         "Name": "Project_Task"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["Id"],
                         "Columns": [
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 128,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Task_Name"
                              },
                              {
                                   "Length": 25,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Type"
                              }
                         ],
                         "Name": "Task"
                    },
                    {
                         "Relationships": {"ManyToOne": [
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "Project_Task_id",
                                        "TargetObject_Attribute": "id"
                                   }],
                                   "TargetObject": "Project_Task",
                                   "Cascade": "false"
                              },
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "Time_Type_Id",
                                        "TargetObject_Attribute": "Id"
                                   }],
                                   "TargetObject": "Time_Type",
                                   "Cascade": "false"
                              }
                         ]},
                         "Pk_Columns": ["Id"],
                         "Columns": [
                              {
                                   "Length": 256,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Activity_Description"
                              },
                              {
                                   "Length": 4,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Actual_Hours"
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Created_On"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Date"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employee_Id"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "End_Time"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Project_Task_id"
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Project_Task_Type"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Start_Time"
                              },
                              {
                                   "Length": 1,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "StatusId"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Timesheet_Id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Time_Type_Id"
                              }
                         ],
                         "Name": "Time_Entry"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "Employee_Id",
                              "Id"
                         ],
                         "Columns": [
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Code"
                              },
                              {
                                   "Length": 256,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Description"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employee_Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 1,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "ISOVERTIME"
                              },
                              {
                                   "Length": 128,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Name"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Time_Type_Category_Id"
                              }
                         ],
                         "Name": "Time_Type"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "Employee_Id",
                              "ID"
                         ],
                         "Columns": [
                              {
                                   "Length": 256,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Description"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employee_Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "ID",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Type"
                              }
                         ],
                         "Name": "Time_Type_Category"
                    },
                    {
                         "Relationships": {"OneToMany": [
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "Id",
                                        "TargetObject_Attribute": "Timesheet_Id"
                                   }],
                                   "TargetObject": "Timesheet_Note",
                                   "Cascade": "false"
                              },
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "Id",
                                        "TargetObject_Attribute": "Timesheet_Id"
                                   }],
                                   "TargetObject": "Time_Entry",
                                   "Cascade": "false"
                              },
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "Id",
                                        "TargetObject_Attribute": "Timesheet_Id"
                                   }],
                                   "TargetObject": "Timesheet_Audit",
                                   "Cascade": "false"
                              }
                         ]},
                         "Pk_Columns": ["Id"],
                         "Columns": [
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employee_Id"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "End_Date"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "lastmodified"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "latitude"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "longitude"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Start_Date"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Status_Id"
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "SubmittedOn"
                              }
                         ],
                         "Name": "Timesheet"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["Id"],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Created_On"
                              },
                              {
                                   "Length": 128,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Description"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "employee_id"
                              },
                              {
                                   "Length": 128,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Error_Msg"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Status_Id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Timesheet_Id"
                              }
                         ],
                         "Name": "Timesheet_Audit"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "Employee_Id",
                              "id"
                         ],
                         "Columns": [
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Definition"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employee_Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 3,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "double",
                                   "Name": "Future_Timesheets"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 1,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "softdeletedflag"
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "TIMESTAMP"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Week_Start_Day"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Year_Start_Date"
                              }
                         ],
                         "Name": "Timesheet_Definition"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "Employee_Id",
                              "Id",
                              "Timesheet_Id"
                         ],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Added_On"
                              },
                              {
                                   "Length": 256,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Comments"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employee_Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Timesheet_Id",
                                   "IsPrimaryKey": true
                              }
                         ],
                         "Name": "Timesheet_Note"
                    }
               ],
               "Strategy": "OTA_SYNC",
               "ScopeDatabaseName": "1000000020ac26b7c",
               "DataSource": "9ea5d226-dc04-46d8-9063-cce30ebd9a59"
          },
          {
               "ScopeName": "Notifications",
               "ScopeTables": [
                    {
                         "Relationships": {"ManyToOne": [{
                              "RelationshipAttributes": [{
                                   "SourceObject_Attribute": "notification_id",
                                   "TargetObject_Attribute": "notification_id"
                              }],
                              "TargetObject": "notification_data",
                              "Cascade": "false"
                         }]},
                         "Pk_Columns": [
                              "employee_id",
                              "notification_id"
                         ],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 150,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "description"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "employee_id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 15,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "module"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "notification_id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 15,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "title"
                              }
                         ],
                         "Name": "notification"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "id",
                              "notification_id"
                         ],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 15,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "data_key"
                              },
                              {
                                   "Length": 255,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "data_value"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "notification_id",
                                   "IsPrimaryKey": true
                              }
                         ],
                         "Name": "notification_data"
                    }
               ],
               "Strategy": "OTA_SYNC",
               "ScopeDatabaseName": "1000000020ac26b7c",
               "DataSource": "f8b0857c-56f4-474e-9dbd-81ca7be58cef"
          }
     ],
     "ArrayOfDataSource": [
          {
               "ID": "b66987d8-93f4-42d2-8485-74a049499092",
               "type": "MIDDLEWARE"
          },
          {
               "ID": "9ea5d226-dc04-46d8-9063-cce30ebd9a59",
               "type": "MIDDLEWARE"
          },
          {
               "ID": "f8b0857c-56f4-474e-9dbd-81ca7be58cef",
               "type": "MIDDLEWARE"
          }
     ]
}
//**********************************End Scope definition************************
