CREATE TABLE `Configurations`(
	`CreatedBy` VARCHAR(32),
	`CreatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
	`id` BIGINT NOT NULL AUTO_INCREMENT,
	`key` VARCHAR(10),
	`LastUpdatedBy` VARCHAR(32),
	`LastUpdatedDateTime` DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3),
	`SoftDeleteFlag` BOOLEAN,
	`value` VARCHAR(10),
	PRIMARY KEY(`id`)
);
ALTER TABLE `Configurations`
	ADD CONSTRAINT `16dfdf04d8e12da375d126a9e121e8` UNIQUE KEY(`id`);
