if(typeof(com)=== "undefined"){ com = {}; }
if(typeof(com.kony)=== "undefined"){ com.kony = {}; }
if(typeof(com.kony.Employee)=== "undefined"){ com.kony.Employee = {}; }
if(typeof(com.kony.Employee.Employee)=== "undefined"){ com.kony.Employee.Employee = {}; }

//API call will trigger Employee reset
com.kony.Employee.Employee.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("Employee",successcallback,errorcallback);
}



if(typeof(com)=== "undefined"){ com = {}; }
if(typeof(com.kony)=== "undefined"){ com.kony = {}; }
if(typeof(com.kony.MYLEAVE)=== "undefined"){ com.kony.MYLEAVE = {}; }
if(typeof(com.kony.MYLEAVE.MYLEAVE)=== "undefined"){ com.kony.MYLEAVE.MYLEAVE = {}; }

//API call will trigger MYLEAVE reset
com.kony.MYLEAVE.MYLEAVE.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("MYLEAVE",successcallback,errorcallback);
}



if(typeof(Notifications)=== "undefined"){ Notifications = {}; }

//API call will trigger Notifications reset
Notifications.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("Notifications",successcallback,errorcallback);
}




// **********************************Start Scope definition************************
konysyncClientSyncConfig ={
     "AppID": "100000002f852f9b9",
     "Version": "80d35f15eb8e81e8a72219996b67a34f761810e18be66a68e522bdc1ce8b3286",
     "ArrayOfSyncScope": [
          {
               "ScopeName": "Employee",
               "ScopeTables": [
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "Communication_Type_Id",
                              "Employee_Id"
                         ],
                         "Columns": [
                              {
                                   "Length": 4,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Communication_Type_Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employee_Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "END_DATE"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "START_DATE"
                              },
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Value"
                              }
                         ],
                         "Name": "Communication_Channel"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "Employee_Id",
                              "Id"
                         ],
                         "Columns": [
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employee_Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 4,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Type"
                              }
                         ],
                         "Name": "Communication_Type"
                    },
                    {
                         "Relationships": {"ManyToOne": [
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "Id",
                                        "TargetObject_Attribute": "Employee_Id"
                                   }],
                                   "TargetObject": "Communication_Channel",
                                   "Cascade": "false"
                              },
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "Media_Id",
                                        "TargetObject_Attribute": "name"
                                   }],
                                   "TargetObject": "mediaEmployee",
                                   "Cascade": "false"
                              }
                         ]},
                         "Pk_Columns": [
                              "Id",
                              "User_Id"
                         ],
                         "Columns": [
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Blood_group"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "date",
                                   "Name": "Date_of_birth"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Department_Id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Designation_Id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employment_Type"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "First_Name"
                              },
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Gender"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "group_id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 255,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Interests"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "IsEmployee"
                              },
                              {
                                   "Length": 64,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Job_Location"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "date",
                                   "Name": "JoiningDate"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Last_Name"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Manager_Id"
                              },
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Marital_Status_Id"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "date",
                                   "Name": "Marriage_date"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Media_Id"
                              },
                              {
                                   "Length": 255,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Medical_needs"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Middle_Name"
                              },
                              {
                                   "Length": 100,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Nationality"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Office_Id"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Physical_disability"
                              },
                              {
                                   "Length": 100,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Place_of_birth"
                              },
                              {
                                   "Length": 100,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Preffered_name"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "RH_factor"
                              },
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Suffix"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Title"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "User_Id",
                                   "IsPrimaryKey": true
                              }
                         ],
                         "Name": "Employee"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["Holiday_Date"],
                         "Columns": [
                              {
                                   "Length": 10,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Holiday_Date",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Name"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Type"
                              }
                         ],
                         "Name": "Holiday"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["Id"],
                         "Columns": [
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "lastmodifiedts"
                              },
                              {
                                   "Length": 1,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "softdeleteflag"
                              },
                              {
                                   "Length": 255,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Status_Name"
                              }
                         ],
                         "Name": "Status"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["name"],
                         "Columns": [
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "classField"
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "classValue"
                              },
                              {
                                   "Length": 60,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "description"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "extension"
                              },
                              {
                                   "Length": 20,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "group"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "true",
                                   "type": "string",
                                   "Name": "name",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 20,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "ondemand"
                              },
                              {
                                   "Length": 15,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "type"
                              },
                              {
                                   "IsNullable": true,
                                   "type": "integer",
                                   "Name": "blobref_url"
                              },
                              {
                                   "metadata": {
                                        "extension": "extension",
                                        "format": "type",
                                        "description": "description",
                                        "id": "name",
                                        "contentType": "URL"
                                   },
                                   "Length": 0,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "binary",
                                   "downloadToDevice": "ondemand",
                                   "downloadToDeviceField": "ondemand",
                                   "Name": "url"
                              }
                         ],
                         "Name": "mediaEmployee"
                    }
               ],
               "Strategy": "OTA_SYNC",
               "ScopeDatabaseName": "100000002f852f9b9",
               "DataSource": "b66987d8-93f4-42d2-8485-74a049499092"
          },
          {
               "ScopeName": "MYLEAVE",
               "ScopeTables": [
                    {
                         "Relationships": {},
                         "Pk_Columns": ["leave_type_id"],
                         "Columns": [
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "availed"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "balance"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "employee_id"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "expiry_date"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "lastmodifiedts"
                              },
                              {
                                   "Length": 4,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "leave_type_id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 100,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "leave_type_name"
                              }
                         ],
                         "Name": "employee_leave_type"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "id",
                              "region_id"
                         ],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "holiday_date"
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "name"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "region_id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "type_id"
                              }
                         ],
                         "Name": "event"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Name"
                              }
                         ],
                         "Name": "event_type"
                    },
                    {
                         "Relationships": {"OneToMany": [
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "id",
                                        "TargetObject_Attribute": "leavel_id"
                                   }],
                                   "TargetObject": "leave_attachments",
                                   "Cascade": "false"
                              },
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "id",
                                        "TargetObject_Attribute": "leave_id"
                                   }],
                                   "TargetObject": "leave_audit",
                                   "Cascade": "false"
                              },
                              {
                                   "RelationshipAttributes": [
                                        {
                                             "SourceObject_Attribute": "employee_id",
                                             "TargetObject_Attribute": "employee_id"
                                        },
                                        {
                                             "SourceObject_Attribute": "id",
                                             "TargetObject_Attribute": "leave_id"
                                        }
                                   ],
                                   "TargetObject": "leave_note",
                                   "Cascade": "false"
                              }
                         ]},
                         "Pk_Columns": [
                              "employee_id",
                              "id"
                         ],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "employee_id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "end_date"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "end_time"
                              },
                              {
                                   "Length": 30,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "lastmodifiedts"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "leave_type_id"
                              },
                              {
                                   "Length": 5,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "double",
                                   "Name": "no_of_hours"
                              },
                              {
                                   "Length": 300,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "reason_desc"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "recurrence_id"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "start_date"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "start_time"
                              },
                              {
                                   "Length": 3,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "status_id"
                              }
                         ],
                         "Name": "leave"
                    },
                    {
                         "Relationships": {"ManyToOne": [{
                              "RelationshipAttributes": [{
                                   "SourceObject_Attribute": "media_id",
                                   "TargetObject_Attribute": "name"
                              }],
                              "TargetObject": "MyLeaveMedia",
                              "Cascade": "false"
                         }]},
                         "Pk_Columns": [
                              "leavel_id",
                              "LV_ATTCH_SEQNO"
                         ],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "lastmodifiedts"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "leavel_id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "double",
                                   "Name": "LV_ATTCH_SEQNO",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "media_id"
                              },
                              {
                                   "Length": 1,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "softdeleteflag"
                              }
                         ],
                         "Name": "leave_attachments"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 255,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "description"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "employee_id"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "error_message"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "lastmodifiedts"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "leave_id"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "status_id"
                              }
                         ],
                         "Name": "leave_audit"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "createdts",
                              "employee_id",
                              "leave_id"
                         ],
                         "Columns": [
                              {
                                   "Length": 255,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "comments"
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "employee_id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "leave_id",
                                   "IsPrimaryKey": true
                              }
                         ],
                         "Name": "leave_note"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 12,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "is_recurrable"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "lastmodifiedts"
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "name"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "sofsdeleteflag"
                              }
                         ],
                         "Name": "leave_type"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["name"],
                         "Columns": [
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "classField"
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "classValue"
                              },
                              {
                                   "Length": 60,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "description"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "extension"
                              },
                              {
                                   "Length": 20,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "group"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "true",
                                   "type": "string",
                                   "Name": "name",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 20,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "ondemand"
                              },
                              {
                                   "Length": 15,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "type"
                              },
                              {
                                   "IsNullable": true,
                                   "type": "integer",
                                   "Name": "blobref_url"
                              },
                              {
                                   "metadata": {
                                        "extension": "extension",
                                        "format": "type",
                                        "description": "description",
                                        "id": "name",
                                        "contentType": "URL"
                                   },
                                   "Length": 0,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "binary",
                                   "downloadToDevice": "ifrecordvalue",
                                   "downloadToDeviceField": "ondemand",
                                   "Name": "url"
                              }
                         ],
                         "Name": "MyLeaveMedia"
                    }
               ],
               "Strategy": "OTA_SYNC",
               "ScopeDatabaseName": "100000002f852f9b9",
               "DataSource": "0e062532-31b4-4816-ba44-23ba12a0dd0c"
          },
          {
               "ScopeName": "Notifications",
               "ScopeTables": [
                    {
                         "Relationships": {"ManyToOne": [{
                              "RelationshipAttributes": [{
                                   "SourceObject_Attribute": "notification_id",
                                   "TargetObject_Attribute": "notification_id"
                              }],
                              "TargetObject": "notification_data",
                              "Cascade": "false"
                         }]},
                         "Pk_Columns": [
                              "employee_id",
                              "notification_id"
                         ],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 150,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "description"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "employee_id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 15,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "module"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "notification_id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 15,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "title"
                              }
                         ],
                         "Name": "notification"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "id",
                              "notification_id"
                         ],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 15,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "data_key"
                              },
                              {
                                   "Length": 255,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "data_value"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "notification_id",
                                   "IsPrimaryKey": true
                              }
                         ],
                         "Name": "notification_data"
                    }
               ],
               "Strategy": "OTA_SYNC",
               "ScopeDatabaseName": "100000002f852f9b9",
               "DataSource": "f8b0857c-56f4-474e-9dbd-81ca7be58cef"
          }
     ],
     "ArrayOfDataSource": [
          {
               "ID": "b66987d8-93f4-42d2-8485-74a049499092",
               "type": "MIDDLEWARE"
          },
          {
               "ID": "0e062532-31b4-4816-ba44-23ba12a0dd0c",
               "type": "MIDDLEWARE"
          },
          {
               "ID": "f8b0857c-56f4-474e-9dbd-81ca7be58cef",
               "type": "MIDDLEWARE"
          }
     ]
}
//**********************************End Scope definition************************
