if(typeof(com)=== "undefined"){ com = {}; }
if(typeof(com.kony)=== "undefined"){ com.kony = {}; }
if(typeof(com.kony.Translation)=== "undefined"){ com.kony.Translation = {}; }
if(typeof(com.kony.Translation.Translation)=== "undefined"){ com.kony.Translation.Translation = {}; }

//API call will trigger Translation reset
com.kony.Translation.Translation.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("Translation",successcallback,errorcallback);
}



if(typeof(com)=== "undefined"){ com = {}; }
if(typeof(com.kony)=== "undefined"){ com.kony = {}; }
if(typeof(com.kony.MYAPPROVALS)=== "undefined"){ com.kony.MYAPPROVALS = {}; }
if(typeof(com.kony.MYAPPROVALS.MYAPPROVALS)=== "undefined"){ com.kony.MYAPPROVALS.MYAPPROVALS = {}; }

//API call will trigger MYAPPROVALS reset
com.kony.MYAPPROVALS.MYAPPROVALS.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("MYAPPROVALS",successcallback,errorcallback);
}



if(typeof(com)=== "undefined"){ com = {}; }
if(typeof(com.ess)=== "undefined"){ com.ess = {}; }
if(typeof(com.ess.EMPLOYEE)=== "undefined"){ com.ess.EMPLOYEE = {}; }
if(typeof(com.ess.EMPLOYEE.Employee)=== "undefined"){ com.ess.EMPLOYEE.Employee = {}; }

//API call will trigger Employee reset
com.ess.EMPLOYEE.Employee.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("Employee",successcallback,errorcallback);
}



if(typeof(com)=== "undefined"){ com = {}; }
if(typeof(com.kony)=== "undefined"){ com.kony = {}; }
if(typeof(com.kony.MYAPPROVALS)=== "undefined"){ com.kony.MYAPPROVALS = {}; }
if(typeof(com.kony.MYAPPROVALS.Notifications)=== "undefined"){ com.kony.MYAPPROVALS.Notifications = {}; }

//API call will trigger Notifications reset
com.kony.MYAPPROVALS.Notifications.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("Notifications",successcallback,errorcallback);
}



if(typeof(com)=== "undefined"){ com = {}; }
if(typeof(com.kony)=== "undefined"){ com.kony = {}; }
if(typeof(com.kony.NotificationsLanguageService)=== "undefined"){ com.kony.NotificationsLanguageService = {}; }
if(typeof(com.kony.NotificationsLanguageService.NotificationsLanguageService)=== "undefined"){ com.kony.NotificationsLanguageService.NotificationsLanguageService = {}; }

//API call will trigger NotificationsLanguageService reset
com.kony.NotificationsLanguageService.NotificationsLanguageService.reset = function(successcallback,errorcallback){
	if(!kony.sync.isSyncInitialized(errorcallback)){
		return;
	}
	kony.sync.scopeReset("NotificationsLanguageService",successcallback,errorcallback);
}




// **********************************Start Scope definition************************
konysyncClientSyncConfig ={
     "AppID": "100004737b2bb0f56",
     "Version": "857b5cd799c4bdc10044de8b74113027444c9810aca13c837f3b9f19c17dca70",
     "ArrayOfSyncScope": [
          {
               "ScopeName": "Translation",
               "ScopeTables": [{
                    "Relationships": {},
                    "Pk_Columns": [
                         "SPRAS",
                         "TEXT_CODE",
                         "TEXT_TYPE"
                    ],
                    "Columns": [
                         {
                              "Length": 1,
                              "IsNullable": false,
                              "Autogenerated": "false",
                              "type": "string",
                              "Name": "SPRAS",
                              "IsPrimaryKey": true
                         },
                         {
                              "Length": 80,
                              "IsNullable": false,
                              "Autogenerated": "false",
                              "type": "string",
                              "Name": "TEXT_CODE",
                              "IsPrimaryKey": true
                         },
                         {
                              "Length": 80,
                              "IsNullable": true,
                              "Autogenerated": "false",
                              "type": "string",
                              "Name": "TEXT_DISPLAY"
                         },
                         {
                              "Length": 12,
                              "IsNullable": false,
                              "Autogenerated": "false",
                              "type": "string",
                              "Name": "TEXT_TYPE",
                              "IsPrimaryKey": true
                         }
                    ],
                    "Name": "Translation"
               }],
               "Strategy": "OTA_SYNC",
               "ScopeDatabaseName": "100004737b2bb0f56",
               "DataSource": "9e00f590-27a0-4205-a83d-8fc6b48dd158"
          },
          {
               "ScopeName": "MYAPPROVALS",
               "ScopeTables": [
                    {
                         "Relationships": {
                              "OneToMany": [{
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "media_id",
                                        "TargetObject_Attribute": "name"
                                   }],
                                   "TargetObject": "ApprovalMedia",
                                   "Cascade": "false"
                              }],
                              "ManyToOne": [{
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "type_id",
                                        "TargetObject_Attribute": "id"
                                   }],
                                   "TargetObject": "attachment_type",
                                   "Cascade": "false"
                              }]
                         },
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "approval_detail_id"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "approval_id"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "media_id"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "type_id"
                              }
                         ],
                         "Name": "approval_attachment"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 128,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "description"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "employee_id"
                              },
                              {
                                   "Length": 128,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "error_msg"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 1,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "request_id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "status_id"
                              }
                         ],
                         "Name": "approval_audit"
                    },
                    {
                         "Relationships": {"OneToMany": [
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "id",
                                        "TargetObject_Attribute": "approval_id"
                                   }],
                                   "TargetObject": "approval_attachment",
                                   "Cascade": "false"
                              },
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "id",
                                        "TargetObject_Attribute": "request_id"
                                   }],
                                   "TargetObject": "approval_audit",
                                   "Cascade": "false"
                              },
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "request_id",
                                        "TargetObject_Attribute": "id"
                                   }],
                                   "TargetObject": "attribute",
                                   "Cascade": "false"
                              },
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "id",
                                        "TargetObject_Attribute": "approval_id"
                                   }],
                                   "TargetObject": "request_approver",
                                   "Cascade": "false"
                              },
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "category_id",
                                        "TargetObject_Attribute": "id"
                                   }],
                                   "TargetObject": "request_category",
                                   "Cascade": "false"
                              },
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "id",
                                        "TargetObject_Attribute": "approval_id"
                                   }],
                                   "TargetObject": "request_note",
                                   "Cascade": "false"
                              }
                         ]},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "category_id"
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 100,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Description"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "due_date"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "employee_id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 1,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "IsLater"
                              },
                              {
                                   "Length": 1,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "IsRead"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "media_id"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "request_date"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "request_id"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "status_id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "type_id"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "leave_hours"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "leave_days"
                              }
                         ],
                         "Name": "approval_request"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 50,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "name"
                              }
                         ],
                         "Name": "attachment_type"
                    },
                    {
                         "Relationships": {"ManyToOne": [{
                              "RelationshipAttributes": [{
                                   "SourceObject_Attribute": "attribute_def_id",
                                   "TargetObject_Attribute": "id"
                              }],
                              "TargetObject": "attribute_def",
                              "Cascade": "false"
                         }]},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "approval_detail_id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "approval_id"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "attribute_def_id"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "value"
                              }
                         ],
                         "Name": "attribute"
                    },
                    {
                         "Relationships": {
                              "OneToMany": [{
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "attribute_section_id",
                                        "TargetObject_Attribute": "id"
                                   }],
                                   "TargetObject": "attribute_section",
                                   "Cascade": "false"
                              }],
                              "ManyToOne": [{
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "data_type_id",
                                        "TargetObject_Attribute": "id"
                                   }],
                                   "TargetObject": "data_type",
                                   "Cascade": "false"
                              }]
                         },
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 12,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "attribute_section_id"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "data_type_id"
                              },
                              {
                                   "Length": 50,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "default_value"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 100,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "label"
                              }
                         ],
                         "Name": "attribute_def"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "description"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "request_type_id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "TYPE"
                              }
                         ],
                         "Name": "attribute_section"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 100,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "description"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              }
                         ],
                         "Name": "data_type"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 256,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "comments"
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "delegation_group_id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "delegator_id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "employee_id"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "end_date"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "request_type_id"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "start_date"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "status_id"
                              }
                         ],
                         "Name": "delegate"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "approval_id",
                              "approver_id"
                         ],
                         "Columns": [
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "approval_id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "approver_id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "delegator_id"
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "lastmodifiedts"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "status_id"
                              }
                         ],
                         "Name": "request_approver"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 50,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "name"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "parent_id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "type_id"
                              }
                         ],
                         "Name": "request_category"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "approval_id"
                              },
                              {
                                   "Length": 200,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "comment"
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "employee_id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "request_type_id"
                              }
                         ],
                         "Name": "request_note"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 50,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "name"
                              }
                         ],
                         "Name": "request_type"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["name"],
                         "Columns": [
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "classField"
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "classValue"
                              },
                              {
                                   "Length": 60,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "description"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "extension"
                              },
                              {
                                   "Length": 20,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "group"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "true",
                                   "type": "string",
                                   "Name": "name",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 20,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "ondemand"
                              },
                              {
                                   "Length": 15,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "type"
                              },
                              {
                                   "IsNullable": true,
                                   "type": "integer",
                                   "Name": "blobref_url"
                              },
                              {
                                   "metadata": {
                                        "extension": "extension",
                                        "format": "type",
                                        "description": "description",
                                        "id": "name",
                                        "contentType": "URL"
                                   },
                                   "Length": 0,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "binary",
                                   "downloadToDevice": "ifrecordvalue",
                                   "downloadToDeviceField": "ondemand",
                                   "Name": "url"
                              }
                         ],
                         "Name": "ApprovalMedia"
                    }
               ],
               "Strategy": "OTA_SYNC",
               "ScopeDatabaseName": "100004737b2bb0f56",
               "DataSource": "38ae6d17-e4f7-4edf-a74d-29339cec8134"
          },
          {
               "ScopeName": "Employee",
               "ScopeTables": [
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "Communication_Type_Id",
                              "Employee_Id"
                         ],
                         "Columns": [
                              {
                                   "Length": 4,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Communication_Type_Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employee_Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "END_DATE"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "START_DATE"
                              },
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Value"
                              }
                         ],
                         "Name": "Communication_Channel"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": [
                              "Employee_Id",
                              "Id"
                         ],
                         "Columns": [
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employee_Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 4,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Type"
                              }
                         ],
                         "Name": "Communication_Type"
                    },
                    {
                         "Relationships": {"ManyToOne": [
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "Id",
                                        "TargetObject_Attribute": "Employee_Id"
                                   }],
                                   "TargetObject": "Communication_Channel",
                                   "Cascade": "false"
                              },
                              {
                                   "RelationshipAttributes": [{
                                        "SourceObject_Attribute": "Media_Id",
                                        "TargetObject_Attribute": "name"
                                   }],
                                   "TargetObject": "mediaEmployee",
                                   "Cascade": "false"
                              }
                         ]},
                         "Pk_Columns": [
                              "Id",
                              "User_Id"
                         ],
                         "Columns": [
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Blood_group"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "date",
                                   "Name": "Date_of_birth"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Department_Id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Designation_Id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Employment_Type"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "First_Name"
                              },
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Gender"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "group_id"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 255,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Interests"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "IsEmployee"
                              },
                              {
                                   "Length": 64,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Job_Location"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "date",
                                   "Name": "JoiningDate"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Last_Name"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Manager_Id"
                              },
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Marital_Status_Id"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "date",
                                   "Name": "Marriage_date"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Media_Id"
                              },
                              {
                                   "Length": 255,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Medical_needs"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Middle_Name"
                              },
                              {
                                   "Length": 100,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Nationality"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Office_Id"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Physical_disability"
                              },
                              {
                                   "Length": 100,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Place_of_birth"
                              },
                              {
                                   "Length": 100,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Preffered_name"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "RH_factor"
                              },
                              {
                                   "Length": 30,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Suffix"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Title"
                              },
                              {
                                   "Length": 12,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "User_Id",
                                   "IsPrimaryKey": true
                              }
                         ],
                         "Name": "Employee"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["Holiday_Date"],
                         "Columns": [
                              {
                                   "Length": 10,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Holiday_Date",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Name"
                              },
                              {
                                   "Length": 10,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Type"
                              }
                         ],
                         "Name": "Holiday"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["Id"],
                         "Columns": [
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "lastmodifiedts"
                              },
                              {
                                   "Length": 1,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "softdeleteflag"
                              },
                              {
                                   "Length": 255,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "Status_Name"
                              }
                         ],
                         "Name": "Status"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["name"],
                         "Columns": [
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "classField"
                              },
                              {
                                   "Length": 40,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "classValue"
                              },
                              {
                                   "Length": 60,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "description"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "extension"
                              },
                              {
                                   "Length": 20,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "group"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "true",
                                   "type": "string",
                                   "Name": "name",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 20,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "ondemand"
                              },
                              {
                                   "Length": 15,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "type"
                              },
                              {
                                   "IsNullable": true,
                                   "type": "integer",
                                   "Name": "blobref_url"
                              },
                              {
                                   "metadata": {
                                        "extension": "extension",
                                        "format": "type",
                                        "description": "description",
                                        "id": "name",
                                        "contentType": "URL"
                                   },
                                   "Length": 0,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "binary",
                                   "downloadToDevice": "ondemand",
                                   "downloadToDeviceField": "ondemand",
                                   "Name": "url"
                              }
                         ],
                         "Name": "mediaEmployee"
                    }
               ],
               "Strategy": "OTA_SYNC",
               "ScopeDatabaseName": "100004737b2bb0f56",
               "DataSource": "27621049-049f-4a61-b74e-d3308961a128"
          },
          {
               "ScopeName": "Notifications",
               "ScopeTables": [
                    {
                         "Relationships": {"OneToMany": [{
                              "RelationshipAttributes": [{
                                   "SourceObject_Attribute": "notification_id",
                                   "TargetObject_Attribute": "notification_id"
                              }],
                              "TargetObject": "notification_data",
                              "Cascade": "false"
                         }]},
                         "Pk_Columns": ["notification_id"],
                         "Columns": [
                              {
                                   "Length": 150,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "description"
                              },
                              {
                                   "Length": 8,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "employee_id"
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "lastmodifiedts"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "notification_id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 15,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "module"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "title"
                              }
                         ],
                         "Name": "notification"
                    },
                    {
                         "Relationships": {},
                         "Pk_Columns": ["id"],
                         "Columns": [
                              {
                                   "Length": 15,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "data_key"
                              },
                              {
                                   "Length": 255,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "data_value"
                              },
                              {
                                   "Length": 14,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "createdts"
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": false,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "id",
                                   "IsPrimaryKey": true
                              },
                              {
                                   "Length": 32,
                                   "IsNullable": true,
                                   "Autogenerated": "false",
                                   "type": "string",
                                   "Name": "notification_id"
                              }
                         ],
                         "Name": "notification_data"
                    }
               ],
               "Strategy": "OTA_SYNC",
               "ScopeDatabaseName": "100004737b2bb0f56",
               "DataSource": "64fec22a-796e-4c79-99ab-157cf56ce584"
          },
          {
               "ScopeName": "NotificationsLanguageService",
               "ScopeTables": [{
                    "Relationships": {},
                    "Pk_Columns": ["okta_user_id"],
                    "Columns": [
                         {
                              "Length": 10,
                              "IsNullable": false,
                              "Autogenerated": "false",
                              "type": "string",
                              "Name": "okta_user_id",
                              "IsPrimaryKey": true
                         },
                         {
                              "Length": 10,
                              "IsNullable": true,
                              "Autogenerated": "false",
                              "type": "string",
                              "Name": "language"
                         },
                         {
                              "Length": 14,
                              "IsNullable": true,
                              "Autogenerated": "false",
                              "type": "string",
                              "Name": "lastmodifiedts"
                         },
                         {
                              "Length": 1,
                              "IsNullable": true,
                              "Autogenerated": "false",
                              "type": "string",
                              "Name": "softdeleteflag"
                         }
                    ],
                    "Name": "languageConfiguration"
               }],
               "Strategy": "OTA_SYNC",
               "ScopeDatabaseName": "100004737b2bb0f56",
               "DataSource": "8839575d-0cf0-4e6c-8e3b-9cfa0a81a7e0"
          }
     ],
     "ArrayOfDataSource": [
          {
               "ID": "9e00f590-27a0-4205-a83d-8fc6b48dd158",
               "type": "MIDDLEWARE"
          },
          {
               "ID": "38ae6d17-e4f7-4edf-a74d-29339cec8134",
               "type": "MIDDLEWARE"
          },
          {
               "ID": "27621049-049f-4a61-b74e-d3308961a128",
               "type": "MIDDLEWARE"
          },
          {
               "ID": "64fec22a-796e-4c79-99ab-157cf56ce584",
               "type": "MIDDLEWARE"
          },
          {
               "ID": "8839575d-0cf0-4e6c-8e3b-9cfa0a81a7e0",
               "type": "MIDDLEWARE"
          }
     ]
}
//**********************************End Scope definition************************
